# Generated by Django 4.1 on 2022-08-03 18:02

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('operator_code', models.IntegerField(verbose_name='Код оператора')),
                ('time_zone', timezone_field.fields.TimeZoneField(choices_display='WITH_GMT_OFFSET')),
            ],
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_start', models.DateTimeField()),
                ('mes_text', models.TextField(verbose_name='Текст сообщения')),
                ('operator_code', models.IntegerField(verbose_name='Код оператора')),
                ('datetime_finish', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время отправки')),
                ('sent', models.BooleanField(default=False)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailer.client')),
                ('distribution_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailer.distribution')),
            ],
        ),
        migrations.AddField(
            model_name='distribution',
            name='tag',
            field=models.ManyToManyField(to='mailer.tag'),
        ),
        migrations.AddField(
            model_name='client',
            name='tag',
            field=models.ManyToManyField(to='mailer.tag'),
        ),
    ]
